#!/bin/bash
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FI=$BASEDIR/back.jpg
FO=$BASEDIR/back_date.jpg
#print date and time
TH='"'$(date "+%H:%M")'"'
TM1='"'$(date "+%A")'"'
TM2='"'$(date "+%d de %B")'"'
#TM1='"domingo"'
#TM2='"30 de septiembre"'
CFH="white"
CFM="#F6FFAA"
CB="back"
CS="rgba(0,0,0,0.5)"
#convert -font Digital-7-MonoItalic -gravity SouthEast -pointsize 120 -fill $CS -draw "rectangle 1585,900 1980,1005" -fill $CB -draw "text +33,+108 $TH" -fill $CFH -draw "text +35,+110 $TH" -font Ubuntu-Condensed -pointsize 40 -fill $CB -draw "text +38,+23 $TM" -fill $CFM -draw "text +40,+25 $TM" $FI $FO
#convert -font Digital-7-MonoItalic -pointsize 120 -fill $CS -draw "rectangle 1490,900 1910,1070" -draw "rectangle 1500,910 1900,1015" -fill $CB -draw "text 1562,1002 $TH" -fill $CFH -draw "text 1560,1000 $TH" -font Ubuntu-Condensed -pointsize 40 -fill $CB -draw "text 1505,1057 $TM" -fill $CFM -draw "text 1503,1055 $TM" $FI $FO
convert -gravity NorthWest -font Digital-7-MonoItalic -pointsize 120 -fill $CS -draw "rectangle 1490,900 1910,1070" -draw "rectangle 1500,910 1900,1015" -fill $CB -draw "text 1562,917 $TH" -fill $CFH -draw "text 1560,915 $TH" -font Ubuntu-Condensed -pointsize 40 -fill $CB -draw "text 1504,1022 $TM1" -fill $CFM -draw "text 1502,1020 $TM1" -gravity SouthEast -fill $CB -draw "text 17,13 $TM2" -fill $CFM -draw "text 19,15 $TM2" $FI $FO
gsettings set org.mate.background picture-filename $FO 2> /dev/null
